#!/bin/bash
#SBATCH --job-name=s3_data_transfer
#SBATCH --partition=u1-service
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=02:00:00
#SBATCH --account=epic
#SBATCH --output=log.s3_transfer_%j.out

set -x

# Activate your custom conda environment
EAGLEhome=/scratch5/purged/Wei.Huang/src/EAGLE
source ${EAGLEhome}/conda/etc/profile.d/conda.sh
eval "$(mamba shell hook --shell bash)"
mamba activate anemoi

# Define the processing logic as a standard Bash function
process_hour() {
   local YYYY=$1
   local MM=$2
   local DD=$3
   local HH=$4
   local s3dir=$5
   local fdir=$6
   local res=$7
   local fcst=$8

   local iflnm=gfs.t${HH}z.pgrb2b.${res}.${fcst}
   local tflnm=tmp_${YYYY}${MM}${DD}.gfs.t${HH}z.pgrb2.${res}.${fcst}
   local ncflnm=regular_grid/gfs.${YYYY}${MM}${DD}.t${HH}z.${res}.${fcst}.nc
   local mlgridflnm=icosahedral_grid/global_icosahedral_m4.${YYYY}${MM}${DD}.t${HH}z.${res}.${fcst}.nc

   if [ ! -f "${mlgridflnm}" ]; then
      if [ ! -f "${ncflnm}" ]; then
         if [ ! -f "${tflnm}" ]; then
            aws s3 cp --no-sign-request "${s3dir}/${fdir}/${HH}/atmos/${iflnm}" "${tflnm}"
         fi

         python interpolate_to_heights.py -i "${tflnm}" -o "${ncflnm}"
         rm -f "${tflnm}" *.idx
      fi

      # Run the icosahedral interpolation
      python interpolate_to_logstate_icosahedral.py \
         --input "${ncflnm}" \
         --mesh ./graph/global_icosahedral_mesh_m4.nc \
         --output "${mlgridflnm}"
   fi
}

# Export the function and variables so subshells spawned by xargs can read them
export -f process_hour
export s3dir=s3://noaa-gfs-bdp-pds
export res=1p00
export fcst=f006

totalyears=1
startyear=2025
dayinmonth=(31 28 31 30 31 30 31 31 30 31 30 31)

# Function to generate the stream of tasks
generate_tasks() {
   local n=0
   while [ "${n}" -lt "${totalyears}" ]
   do
      local YYYY=$(( startyear + n ))

      if (( (YYYY % 400 == 0) || (YYYY % 4 == 0 && YYYY % 100 != 0) )); then
         dayinmonth[1]=29
      else
         dayinmonth[1]=28
      fi

      local month=1
      while [ $month -le 12 ]
      do
         printf -v MM "%02d" $month
         local nm=$(( month - 1 ))
         
         local day=1
         while [ $day -le ${dayinmonth[nm]} ]
         do
            printf -v DD "%02d" $day
            local fdir=gfs.${YYYY}${MM}${DD}

            for HH in 00 06 12 18
            do
               # Print arguments separated by space, one task per line
               echo "${YYYY} ${MM} ${DD} ${HH} ${s3dir} ${fdir} ${res} ${fcst}"
            done
            day=$(( day + 1 ))
         done
         month=$(( month + 1 ))
      done
      n=$(( n + 1 ))
   done
}

# Stream tasks into xargs to run exactly 16 concurrently
generate_tasks | xargs -P 16 -n 8 bash -c 'process_hour "$@"' _

exit 0

Why this xargs approach works better:export -f process_hour: xargs runs commands inside a new process. Exporting the function allows the underlying bash -c calls to recognize and execute it.-P 16: Instructs GNU xargs to maintain exactly 16 concurrent processes. It handles the queuing automatically.-n 8: Tells xargs to grab exactly 8 arguments at a time from the input stream (which corresponds to one full line generated by echo) and pass them to a single execution of process_hour.The trailing _: In bash -c '...' _ arg1 arg2, the underscore acts as a placeholder for $0, ensuring your variables correctly map to $1 (YYYY), $2 (MM), etc.printf -v: Cleaned up the leading-zero padding logic using built-in bash formatting instead of string checking.Would you like to modify the script to log the outputs of each worker into distinct files to track their individual download speeds?Hacker NewsGNU Parallel, where have you been all my life?Aug 21, 2023 — Well, the idea would be to replace a lot of your pipe usage. Off the wall, but Scala has a concise syntax for process operations, ...Super Userfind/xargs, filenames with spaces, and quotesJan 17, 2015 — Well, the point of xargs is that it lets me run 8 jobs on 8 cores, with bash I could have them run serially or to fork 1,800 proce...Super Userunix - using xargs to cd to a directoryNov 3, 2010 — There are two problems with your code: xargs cannot run cd because cd is a built-in command and xargs can run only executable file...Show all
